Demo CITI Preview Mode

diff --git a/wazideploy-samples/Jenkins/static-build-upload-download-deploy-python.jenkinsfile b/wazideploy-samples/Jenkins/static-build-upload-download-deploy-python.jenkinsfile
--- a/wazideploy-samples/Jenkins/static-build-upload-download-deploy-python.jenkinsfile
+++ b/wazideploy-samples/Jenkins/static-build-upload-download-deploy-python.jenkinsfile
@@ -99,6 +99,137 @@ pipeline {
             }
         }
 
+        stage('ZCodeScan COBOL Static Scan') {
+           environment {
+              SONARQ_CREDS = credentials("$SONARQ_CRED_ID")
+            }
+            steps {
+                script{
+                    // DBB Build Preview
+                    def buildListContents = []
+                    node (zOsAgentLabel) {
+                        def rc = sh (returnStatus: true, script: '''#!/bin/sh
+                             if [[ $DBB_BUILD_TYPE == *Build ]]
+                            then
+                                export DBB_CONF=${WORKSPACE}/${APP_NAME}/dbb-build
+                                CMD="$DBB_HOME/bin/groovyz $GROOVYZ_BUILD_EXTRA_OPTS\
+                                    ${WORKSPACE}/dbb-zappbuild/build.groovy --logEncoding UTF-8 -w ${WORKSPACE}\
+                                    --workDir ${WORKSPACE}/BUILD-${BUILD_NUMBER} --hlq ${DBB_HLQ}\
+                                    ${DBB_BUILD_TYPE} ${BUILD_VERBOSE} ${DBB_BUILD_EXTRA_OPTS}\
+                                    --application ${APP_NAME} --sourceDir ${WORKSPACE} --preview"
+                                echo "$CMD"
+                                $CMD
+                                rc=$?
+                            else
+                                export DBB_BUILD=${WORKSPACE}/${APP_NAME}/dbb-build
+                                export DBB_CONF=${DBB_BUILD}
+                                export PATH=$DBB_HOME/bin:$PATH
+                                cd ${WORKSPACE}/${APP_NAME}
+                                CMD="dbb -cp $HOME/db2/db2jcc4.jar build ${DBB_BUILD_TYPE} --log-encoding UTF-8 --hlq ${DBB_HLQ}\
+                                         --config $DBB_BUILD/dbb-app.yaml\
+                                         --dbid db2inst1 --dbpf $HOME/password --preview"
+                                mkdir -p ${WORKSPACE}/BUILD-${BUILD_NUMBER}/build.${BUILD_NUMBER}
+                                echo "$CMD"
+                                $CMD
+                                rc=$?
+                                mv logs/* ${WORKSPACE}/BUILD-${BUILD_NUMBER}/build.${BUILD_NUMBER}
+                            fi
+                            exit $rc
+                            ''')
+                        if ( rc != 0 )
+                            error("DBB build failed!!!")
+                        rc = sh (returnStatus: true, script: '''#!/bin/sh
+                                cd ${WORKSPACE}
+                                . /u/jenkins/python_wazideploy/beta/env/bin/activate
+                                export JAVA_HOME=/usr/lpp/java/J21.0_64
+                                CMD="zcodescan \
+                                        -e IBM-1047 \
+                                        -sfl ${WORKSPACE}/BUILD-${BUILD_NUMBER}/build.${BUILD_NUMBER}/buildList.txt \
+                                        -if $PWD\
+                                        -rf cics-genapp/zcodescan-rules.yaml\
+                                        -cf $HOME/config.yml\
+                                        -of ${WORKSPACE}/BUILD-${BUILD_NUMBER}/build.${BUILD_NUMBER}/zcodescan-cics-genapp.yml\
+                                        -et sonarqube -ef ${WORKSPACE}/BUILD-${BUILD_NUMBER}/build.${BUILD_NUMBER}/zcodescan-cics-genapp-sonarqube.json"
+                                echo "$CMD"
+                                zcodescan -v
+                                $CMD
+                                rc=$?
+                                chtag -t -c UTF-8 ${WORKSPACE}/BUILD-${BUILD_NUMBER}/build.${BUILD_NUMBER}/zcodescan-cics-genapp-sonarqube.json
+                                chtag -r ${WORKSPACE}/BUILD-${BUILD_NUMBER}/build.${BUILD_NUMBER}/zcodescan-cics-genapp-sonarqube.json
+                                chtag -r ${WORKSPACE}/BUILD-${BUILD_NUMBER}/build.${BUILD_NUMBER}/zcodescan-cics-genapp.yml
+                                if [ $rc -gt 3 ]
+                                then
+                                  exit $rc
+                                elif [ $rc -lt 0 ]
+                                then
+                                  exit $rc
+                                else
+                                 rc=0
+                                fi
+                                exit $rc
+                            ''')
+                        def files = findFiles(glob: "**BUILD-${BUILD_NUMBER}/**/buildList.txt")
+                        // Do not enter into some steps if nothing in the build list
+                        hasBuildFiles = files.length > 0 && files[0].length > 0
+                        if ( hasBuildFiles ) {
+                            files.each { buildList ->
+                                println "Process file: $buildList.path"
+                                def content = readFile file: buildList.path
+                                buildListContents << content
+                            }
+                        }
+                    }
+                    buildListContents.each { content ->
+                        writeFile file: '/tmp/buildList.txt', text:content
+                            def rc = sh (returnStatus: true, script: '''#!/bin/bash
+                                  cd ${WORKSPACE}
+                                  export PATH=/opt/java/jdk-21.0.8/bin:$PATH
+                                  export JAVA_HOME=/opt/java/jdk-21.0.8
+                                  zcodescan -v
+                                  CMD="zcodescan \
+                                    -sfl /tmp/buildList.txt \
+                                    -if $PWD\
+                                    -rf cics-genapp/zcodescan-rules.yaml\
+                                    -cf $HOME/config.yml\
+                                    -of ${WORKSPACE}/BUILD-${BUILD_NUMBER}/build.${BUILD_NUMBER}/zcodescan-cics-genapp.yml\
+                                    -et sonarqube -ef ${WORKSPACE}/BUILD-${BUILD_NUMBER}/build.${BUILD_NUMBER}/zcodescan-cics-genapp-sonarqube.json"
+                                  echo "$CMD"
+                                  $CMD
+                                  rc=$?
+                                  CMD="/opt/sonar/sonar-scanner-7.1.0.4889-linux-x64/bin/sonar-scanner \
+                                        -Dsonar.projectKey=genapp \
+                                        -Dsonar.sources=. \
+                                        -Dsonar.host.url=http://wazi-deploy.rpp.hur.hdclab.intranet.ibm.com:9000 \
+                                        -Dsonar.externalIssuesReportPaths=./BUILD-${BUILD_NUMBER}/build.${BUILD_NUMBER}/zcodescan-cics-genapp-sonarqube.json"
+                                  echo "$CMD"
+                                  $CMD
+                                  if [ $rc -gt 3 ]
+                                  then
+                                    exit $rc
+                                  elif [ $rc -lt 0 ]
+                                  then
+                                    exit $rc
+                                  else
+                                    rc=0
+                                  fi
+                                  exit $rc
+                            ''')
+                        if ( rc != 0 )
+                            error("ZCodeScan failed!!!")
+                    }
+                }
+            }
+            post {
+                always {
+                        dir("${WORKSPACE}/BUILD-${BUILD_NUMBER}") {
+                            archiveArtifacts allowEmptyArchive: true,
+                                            artifacts: '**/zcodescan-cics*',
+                                            onlyIfSuccessful: false
+                    }
+                }
+            }
+        }
+
         stage('DBB Build') {
             when {
                 expression { rollingBack == false } 
